Name:           perl-JSON-RPC-Common
Version:        0.07
Release:        1%{?dist}
Summary:        Transport agnostic JSON RPC helper objects
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/JSON-RPC-Common/
Source0:        http://www.cpan.org/authors/id/N/NU/NUFFIN/JSON-RPC-Common-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(HTTP::Request)
BuildRequires:  perl(JSON) >= 2.11
BuildRequires:  perl(Moose) >= 0.48
BuildRequires:  perl(MooseX::Types)
BuildRequires:  perl(MooseX::Types::Moose)
BuildRequires:  perl(namespace::clean) >= 0.08
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::use::ok)
BuildRequires:  perl(URI::QueryParam)
Requires:       perl(HTTP::Request)
Requires:       perl(JSON) >= 2.11
Requires:       perl(Moose) >= 0.48
Requires:       perl(MooseX::Types)
Requires:       perl(MooseX::Types::Moose)
Requires:       perl(namespace::clean) >= 0.08
Requires:       perl(Test::Exception)
Requires:       perl(Test::use::ok)
Requires:       perl(URI::QueryParam)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides abstractions for JSON-RPC 1.0, 1.1 (both variations)
and 2.0 (formerly 1.2) Procedure Call and Procedure Return objects
(formerly known as request and result), along with error objects. It also
provides marshalling objects to convert the model objects into JSON text
and HTTP requests/responses.

%prep
%setup -q -n JSON-RPC-Common-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jun 17 2010 David Hrbáč <david@hrbac.cz> 0.07-1
- Specfile autogenerated by cpanspec 1.78.
