diff -ur lbzip2.orig/Makefile lbzip2/Makefile
--- lbzip2.orig/Makefile	2009-04-04 00:33:49.000000000 +0200
+++ lbzip2/Makefile	2010-01-06 01:46:10.000000000 +0100
@@ -2,33 +2,29 @@
 .POSIX:
 
 CC=gcc
-CFLAGS=$$($(SHELL) lfs.sh CFLAGS) -D _XOPEN_SOURCE=500 -pipe -ansi -pedantic \
-    -O2
-
-
-
-
-LDFLAGS=-s $$($(SHELL) lfs.sh LDFLAGS)
-LIBS=-l pthread -l bz2 $$($(SHELL) lfs.sh LIBS)
+USE_CFLAGS=$(shell /bin/dash lfs.sh CFLAGS) -D _XOPEN_SOURCE=500 -pipe -ansi \
+  -pedantic $(CFLAGS)
+USE_LDFLAGS=$(LDFLAGS) $(shell /bin/dash lfs.sh LDFLAGS)
+USE_LIBS=$(LIBS) -l pthread -l bz2 $(shell /bin/dash lfs.sh LIBS)
 
 lbzip2: main.o lbzip2.o lbunzip2.o lbunzip2_single.o lacos_rbtree.o
-	$(CC) -o lbzip2 $(LDFLAGS) main.o lbzip2.o lbunzip2.o \
-  lbunzip2_single.o lacos_rbtree.o $(LIBS)
+	$(CC) -o lbzip2 $(USE_LDFLAGS) main.o lbzip2.o lbunzip2.o \
+  lbunzip2_single.o lacos_rbtree.o $(USE_LIBS)
 
 main.o: main.c main.h lbunzip2_single.h lbunzip2.h lbzip2.h
-	$(CC) $(CFLAGS) -c main.c
+	$(CC) $(USE_CFLAGS) -c main.c
 
 lbzip2.o: lbzip2.c main.h lbzip2.h lacos_rbtree.h
-	$(CC) $(CFLAGS) -c lbzip2.c
+	$(CC) $(USE_CFLAGS) -c lbzip2.c
 
 lbunzip2.o: lbunzip2.c main.h lbunzip2.h lacos_rbtree.h
-	$(CC) $(CFLAGS) -c lbunzip2.c
+	$(CC) $(USE_CFLAGS) -c lbunzip2.c
 
 lbunzip2_single.o: lbunzip2_single.c main.h lbunzip2_single.h
-	$(CC) $(CFLAGS) -c lbunzip2_single.c
+	$(CC) $(USE_CFLAGS) -c lbunzip2_single.c
 
 lacos_rbtree.o: lacos_rbtree.c lacos_rbtree.h
-	$(CC) $(CFLAGS) -c lacos_rbtree.c
+	$(CC) $(USE_CFLAGS) -c lacos_rbtree.c
 
 clean:
 	rm -f lbzip2 main.o lbzip2.o lbunzip2.o lbunzip2_single.o \
