# $Id$
# Authority: dag
# Upstream: Malay <malay$bioinformatics,org>

%define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`%{__perl} -V:installvendorarch`"; echo $installvendorarch)

%define real_name ABI

Summary: Perl module to parse chromatogram files
Name: perl-ABI
Version: 1.0
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/ABI/

Source: http://www.cpan.org/authors/id/M/MA/MALAY/ABI-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

BuildArch: noarch
BuildRequires: perl
BuildRequires: perl(Test::More)

%description
Perl module to parse chromatogram files generated by
Applied Biosystems (ABI) automated DNA sequencing machine.

%prep
%setup -n %{real_name}-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{buildroot}%{_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install

### Clean up buildroot
find %{buildroot} -name .packlist -exec %{__rm} {} \;

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc Changes LICENSE MANIFEST META.yml README
%doc %{_mandir}/man3/ABI.3pm*
%{perl_vendorlib}/ABI.pm

%changelog
* Wed Oct 10 2007 Dag Wieers <dag@wieers.com> - 1.0-1
- Initial package. (using DAR)
