# $Id$
# Authority: shuff
# Upstream: Mark Jaroski <markj$cpan,org>

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name WWW-Mediawiki-Client

%define perl_prefix %{buildroot}%{_prefix}

Summary:  Command-line Mediawiki client
Name: perl-WWW-Mediawiki-Client
Version: 0.31
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/WWW-Mediawiki-Client/

Source: http://search.cpan.org/CPAN/authors/id/M/MA/MARKJ/WWW-Mediawiki-Client-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch

BuildRequires: perl
BuildRequires: perl(Carp)
BuildRequires: perl(Data::Dumper)
BuildRequires: perl(Encode) >= 1.75
BuildRequires: perl(Encode::Guess)
BuildRequires: perl(Exception::Class)
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(File::Find)
BuildRequires: perl(File::Spec)
BuildRequires: perl(Getopt::Std)
BuildRequires: perl(HTML::TokeParser)
BuildRequires: perl(HTTP::Cookies)
BuildRequires: perl(HTTP::Message) >= 1.56
BuildRequires: perl(HTTP::Request) >= 1.40
BuildRequires: perl(HTTP::Request::Common) >= 1.26
BuildRequires: perl(LWP)
BuildRequires: perl(Pod::Usage)
BuildRequires: perl(Test::Differences)
BuildRequires: perl(URI) >= 1.31
BuildRequires: perl(VCS::Lite)
BuildRequires: perl(XML::LibXML)
BuildRequires: rpm-macros-rpmforge
Requires: perl(Carp)
Requires: perl(Data::Dumper)
Requires: perl(Encode) >= 1.75
Requires: perl(Encode::Guess)
Requires: perl(Exception::Class)
Requires: perl(File::Find)
Requires: perl(File::Spec)
Requires: perl(Getopt::Std)
Requires: perl(HTML::TokeParser)
Requires: perl(HTTP::Cookies)
Requires: perl(HTTP::Message) >= 1.56
Requires: perl(HTTP::Request) >= 1.40
Requires: perl(HTTP::Request::Common) >= 1.26
Requires: perl(LWP)
Requires: perl(Pod::Usage)
Requires: perl(URI) >= 1.31
Requires: perl(VCS::Lite)
Requires: perl(XML::LibXML)

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

%description
WWW::Mediawiki::Client provides a very simple CVS-like interface for Mediawiki
driven WikiWiki websites, such as Wikitravel or Wikipedia. The interface mimics
the two most basic CVS commands: update and commit with similarly named
methods. Each of these has a shorter alias, as in CVS.

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{perl_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc ChangeLog README TODO
%doc %{_mandir}/man?/*
%{_bindir}/*
%{perl_vendorlib}/WWW/Mediawiki/Client.pm
%{perl_vendorlib}/WWW/Mediawiki/Client/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/*/*/.packlist

%changelog
* Wed Feb 22 2012 Steve Huff <shuff@vecna.org> - 0.31-1
- Initial package.
