# $Id$
# Authority: shuff
# Upstream: Dmitry Ovsyanko <do_$pochta,ru>

# el5 ships perl-Archive-Zip-1.16 
%{?el5:# Tag: rfx}

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name Spreadsheet-XLSX

%define perl_prefix %{buildroot}%{_prefix}

Summary: Read MS Excel 2007 format
Name: perl-Spreadsheet-XLSX
Version: 0.13
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/Spreadsheet-XLSX/

Source: http://search.cpan.org/CPAN/authors/id/D/DM/DMOW/Spreadsheet-XLSX-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch

BuildRequires: perl
BuildRequires: perl(Archive::Zip) >= 1.18
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(Spreadsheet::ParseExcel)
BuildRequires: rpm-macros-rpmforge
Requires: perl
Requires: perl(Archive::Zip) >= 1.18
Requires: perl(Spreadsheet::ParseExcel)

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

%description
This module is a (quick and dirty) emulation of Spreadsheet::ParseExcel for
Excel 2007 (.xlsx) file format. It supports styles and many of Excel's quirks,
but not all. It populates the classes from Spreadsheet::ParseExcel for
interoperability; including Workbook, Worksheet, and Cell.

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{perl_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc Changes README
%doc %{_mandir}/man?/*
%{perl_vendorlib}/Spreadsheet/XLSX.pm
%{perl_vendorlib}/Spreadsheet/XLSX/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/*/.packlist

%changelog
* Tue Oct 11 2011 Steve Huff <shuff@vecna.org> - 0.13-1
- Initial package.
