# $Id$
# Authority: dag

Summary: Video-surveilance system
Name: motion
Version: 3.2.4
Release: 1
License: GPL
Group: Applications/Multimedia
URL: http://motion.sourceforge.net/

Source: http://dl.sf.net/motion/motion-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

BuildRequires: libjpeg-devel, ffmpeg-devel, mysql-devel, postgresql-devel

%description
Motion is a software motion detector. It grabs images from video4linux
devices and/or from webcams (such as the axis network cameras). Motion
is the perfect tool for keeping an eye on your property keeping only
those images that are interesting. Motion is strictly command line
driven and can run as a daemon with a rather small footprint. It is
built with MySQL and PostgreSQL support and mpegs generated by ffmpeg
and http remote control.

%prep
%setup

%build
%configure \
	--sysconfdir="%{_sysconfdir}/motion" \
	--without-libjpeg-mmx \
	--without-optimizecpu

%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} install DESTDIR="%{buildroot}"

%{__perl} -pi.orig -e 's|MOTION-/usr|MOTION-|g' motion.init-RH
%{__install} -D -m0755 motion.init-RH %{buildroot}%{_initrddir}/motion

%{__mv} -f %{buildroot}%{_sysconfdir}/motion/motion-dist.conf %{buildroot}%{_sysconfdir}/motion/motion.conf

%clean
%{__rm} -rf %{buildroot}

%files
%defattr (-, root, root, 0755)
%doc CHANGELOG COPYING CREDITS FAQ INSTALL README* *.conf *.html
%doc %{_mandir}/man1/motion.1*
%config(noreplace) %{_sysconfdir}/motion/
%config %{_initrddir}/motion
%{_bindir}/motion

%changelog
* Mon Feb 06 2006 Dag Wieers <dag@wieers.com> - 3.2.4-1
- Initial package. (using DAR)
