Name:           perl-Apache2-AuthenNIS
Version:        0.15
Release:        1%{?dist}
Summary:        Mod_perl2 NIS Authentication module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Apache2-AuthenNIS/
Source0:        http://www.cpan.org/modules/by-module/Apache2/Apache2-AuthenNIS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(mod_perl2)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Net::NIS)
Requires:       perl(mod_perl2)
Requires:       perl(Net::NIS)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This perl module is designed to work with mod_perl2 and the Net::NIS
module by Rik Haris (rik.harris@fulcrum.com.au). Version 0.13 of
Apache::AuthenNIS was renamed and modified to use mod_perl2. That module
was a direct adaptation of Michael Parker's (parker@austx.tandem.com)
Apache::AuthenSmb module.

%prep
%setup -q -n Apache2-AuthenNIS-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Mar 01 2012 David Hrbáč <david@hrbac.cz> - 0.15-1
- Specfile autogenerated by cpanspec 1.78.
