# $Id$
# Authority: shuff
# Upstream: Tatsuhiko Miyagawa <miyagawa$bulknews,net>
# ExcludeDist: el3 el4

# Plack is rfx on el6
%{?el6:# Tag: rfx}

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name Tatsumaki

Summary: Non-blocking web framework based on Plack and AnyEvent
Name: perl-Tatsumaki
Version: 0.1013
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/Tatsumaki/

Source: http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/Tatsumaki-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

BuildArch: noarch
BuildRequires: perl >= 5.8.1
BuildRequires: perl(Any::Moose)
BuildRequires: perl(AnyEvent) >= 5.2
BuildRequires: perl(AnyEvent::HTTP)
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(Filter::Util::Call)
BuildRequires: perl(JSON)
BuildRequires: perl(Mouse) >= 0.34
BuildRequires: perl(Plack) >= 0.9913
BuildRequires: perl(Text::MicroTemplate)
BuildRequires: perl(Try::Tiny)
BuildRequires: perl(Twiggy)
BuildRequires: perl(parent)
BuildRequires: rpm-macros-rpmforge
Requires: perl >= 5.8.1
Requires: perl(Any::Moose)
Requires: perl(AnyEvent) >= 5.2
Requires: perl(AnyEvent::HTTP)
Requires: perl(Filter::Util::Call)
Requires: perl(JSON)
Requires: perl(Mouse) >= 0.34
Requires: perl(Plack) >= 0.9913
Requires: perl(Text::MicroTemplate)
Requires: perl(Try::Tiny)
Requires: perl(Twiggy)
Requires: perl(parent)

# don't scan the examples for autoreq/prov
%filter_requires_in %{_docdir}
%filter_provides_in %{_docdir}

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

%description
Tatsumaki is a toy port of Tornado for Perl using Plack (with non-blocking
extensions) and AnyEvent.

It allows you to write a web application that does a immediate response with
template rendering, IO-bound delayed response (like fetching third party API or
XML feeds), server push streaming and long-poll Comet in a clean unified API.

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{buildroot}%{_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc Changes META.yml README eg/
%doc %{_mandir}/man?/*
%{perl_vendorlib}/Tatsumaki.pm
%{perl_vendorlib}/Tatsumaki/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/.packlist

%changelog
* Tue Jul 19 2011 Steve Huff <shuff@vecna.org> - 0.1013-1
- Initial package.
