# $Id$
# Authority: shuff
# Upstream: Alexis Sukrieh <sukria$sukria,net>

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name perlconsole

%define perl_prefix %{buildroot}%{_prefix}

Summary: REPL for Perl
Name: perlconsole
Version: 0.4
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/perlconsole/

Source: http://search.cpan.org/CPAN/authors/id/S/SU/SUKRIA/perlconsole-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch

BuildRequires: perl
BuildRequires: perl(B::Keywords)
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(Getopt::Long)
BuildRequires: perl(Lexical::Persistence)
BuildRequires: perl(Module::Refresh)
BuildRequires: perl(Term::ReadLine::Gnu)
BuildRequires: rpm-macros-rpmforge
Requires: perl
Requires: perl(B::Keywords)
Requires: perl(Getopt::Long)
Requires: perl(Lexical::Persistence)
Requires: perl(Module::Refresh)
Requires: perl(Term::ReadLine::Gnu)

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

%description
Perl Console is a light program that lets you evaluate Perl code interactively.
It uses Readline for grabing input and provides completion with all the
namespaces loaded during your session.

This is pretty useful for Perl developers that write modules. You can load a
module in your session and test a function exported by the module.

Readline is used to grab user input and provides then all the facilities your
are used to : completion, key bindings, ...

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{perl_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc AUTHORS CHANGES COPYING INSTALL README
%doc %{_mandir}/man?/*
%{_bindir}/*
%{perl_vendorlib}/PerlConsole.pm
%{perl_vendorlib}/PerlConsole/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/.packlist

%changelog
* Fri Jun 22 2012 Steve Huff <shuff@vecna.org> - 0.4-1
- Initial package.
