Name:           perl-Taint-Util
Version:        0.08
Release:        1%{?dist}
Summary:        Test for and flip the taint flag without regex matches or eval
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Taint-Util/
Source0:        http://www.cpan.org/authors/id/A/AV/AVAR/Taint-Util-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Wraps perl's internal routines for checking and setting the taint flag and
thus does not rely on regular expressions for untainting or odd tricks
involving eval and kill for checking whether data is tainted, instead it
checks and flips a flag on the scalar in-place.

%prep
%setup -q -n Taint-Util-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog dist.ini LICENSE META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Taint*
%{_mandir}/man3/*

%changelog
* Thu Jun 17 2010 David Hrbáč <david@hrbac.cz> 0.08-1
- Specfile autogenerated by cpanspec 1.78.
