# $Id$
# Authority: dag

### EL6 ships with openmpi-1.4.1-4.3.el6
%{?el6:# Tag: rfx}
### EL5 ships with openmpi-1.4-4.el5
%{?el5:# Tag: rfx}
### EL4 ships with openmpi-1.2.8-4.el4
%{?el4:# Tag: rfx}

Summary: Powerful implementaion of MPI
Name: openmpi
Version: 1.4.2
Release: 1%{?dist}
License: BSD
Group: Development/Libraries
URL: http://www.open-mpi.org/

Source: http://www.open-mpi.org/software/ompi/v1.4/downloads/openmpi-%{version}.tar.bz2
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

Provides: mpi

%description
Open MPI is a project combining technologies and resources from
several other projects (FT-MPI, LA-MPI, LAM/MPI, and PACX-MPI) in
order to build the best MPI library available.

This RPM contains all the tools necessary to compile, link, and run
Open MPI jobs.

%package devel
Summary: Header files, libraries and development documentation for %{name}.
Group: Development/Libraries
Requires: %{name} = %{version}-%{release}

%description devel
This package contains the header files, static libraries and development
documentation for %{name}. If you like to develop programs using %{name},
you will need to install %{name}-devel.

%prep
%setup

%build
%configure
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} install DESTDIR="%{buildroot}"

%{__mkdir_p} %{buildroot}%{_sysconfdir}/modulefiles/openmpi/
cat <<EOF >%{buildroot}%{_sysconfdir}/modulefiles/openmpi/%{version}
#%Module

# NOTE: This is an automatically-generated file!  (generated by the
# Open MPI RPM).  Any changes made here will be lost a) if the RPM is
# uninstalled, or b) if the RPM is upgraded or uninstalled.

proc ModulesHelp { } {
   puts stderr "This module adds Open MPI v%{version} to various paths"
}

module-whatis   "Sets up Open MPI v%{version}  in your enviornment"

prepend-path PATH "%{_prefix}/bin/"
prepend-path LD_LIBRARY_PATH %{_libdir}
prepend-path MANPATH %{_mandir}
EOF

find %{buildroot} -type f -o -type l | \
   sed -e "s@%{buildroot}@@" | \
   egrep "lib.*.so|mca.*so|/vt*|/*otf*|/vampirtrace/|opari" | \
   egrep -v '/vtcc*|/vtcxx*|/vtf77*|/vtf90*' \
   > runtime.files | /bin/true

# Devel files, potentially including VT files
find %{buildroot} -type f -o -type l | \
   sed -e "s@%{buildroot}@@" | \
   egrep "lib.*\.a|lib.*\.la|mpi.*mod|/vtcc*|/vtcxx*|/vtf77*|/vtf90*|*\.SPEC" \
   > devel.files | /bin/true

%clean
%{__rm} -rf %{buildroot}

%files -f runtime.files
%defattr(-, root, root, 0755)
%doc AUTHORS INSTALL LICENSE README VERSION
%doc %{_mandir}
%{_sysconfdir}/modulefiles/
%{_datadir}/openmpi/
%{_bindir}/mpiexec
%{_bindir}/mpirun
%{_bindir}/ompi_info
%{_bindir}/ompi-server
%{_bindir}/orte-clean
%{_bindir}/orte-iof
%{_bindir}/orte-ps
%{_bindir}/orted
%{_bindir}/orterun
%{_libdir}/openmpi/

%files devel -f devel.files
%defattr(-, root, root, 0755)
%{_includedir}
%{_bindir}/mpic++
%{_bindir}/mpicc
%{_bindir}/mpiCC
%{_bindir}/mpicxx
%{_bindir}/mpif77
%{_bindir}/mpif90
%{_bindir}/opal_wrapper

%changelog
* Thu Jun 10 2010 Dag Wieers <dag@wieers.com> - 1.4.2-1
- Initial package. (using DAR)
