# $Id$
# Authority: shuff
# Upstream: Rocco Caputo <rcaputo$cpan,org>

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name Lexical-Persistence

%define perl_prefix %{buildroot}%{_prefix}

Summary: Persistent contexts for lexical variables
Name: perl-Lexical-Persistence
Version: 1.020
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/Lexical-Persistence/

Source: http://search.cpan.org/CPAN/authors/id/R/RC/RCAPUTO/Lexical-Persistence-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch

BuildRequires: perl
BuildRequires: perl(Devel::LexAlias) >= 0.04
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(PadWalker) >= 1.1
BuildRequires: rpm-macros-rpmforge
Requires: perl
Requires: perl(Devel::LexAlias) >= 0.04
Requires: perl(PadWalker) >= 1.1

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

%description
Lexical::Persistence lets your code access persistent data through lexical variables.

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{perl_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc CHANGES META.yml README eg/
%doc %{_mandir}/man?/*
%{perl_vendorlib}/Lexical/Persistence.pm
#%{perl_vendorlib}/Lexical/Persistence/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/*/.packlist

%changelog
* Fri Jun 22 2012 Steve Huff <shuff@vecna.org> - 1.020-1
- Initial package.
