.\"                                      Hey, EMACS: -*- nroff -*-
.TH UNARJ 1 2004-03-12 "3.10" "Arj Software"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
unarj \- Unarchive ARJ files
.SH SYNOPSIS
.B unarj
.RI [ options ] " files" ...
.SH DESCRIPTION
The
.B unarj
command is a simple wrapper to ease transition from the non-free unarj.
.SH OPTIONS
This program has the same command line options as
.BR arj (1).
It also supports to be called without any options as a synonim for
.BR l .
For the full command line list please see
.BR arj (1)
man page.
.SH SEE ALSO
.BR arj (1),
.BR rearj (1).
.SH AUTHOR
This manual page was written by Guillem Jover <guillem@debian.org>.
