#!/bin/sh

# chkconfig: 01356 95 05
# description: Server for Plan calendars.

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.

start () {
	[ -f /var/lock/subsys/netplan ] && exit 1
	echo -n $"Starting networked schedule server: "
	daemon /usr/lib/plan/netplan -v
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && touch /var/lock/subsys/netplan
	return $RETVAL
}

stop () {
	echo -n $"Stopping networked schedule server: "
	killproc netplan
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/netplan
}

case "$1" in
  start)
		start
	;;
  
	stop)
		stop
	;;
  
	status)
		status netplan
	;;
  
	restart|reload)
		stop
		start
	;;
	condrestart)
		if [ -f /var/lock/subsys/netplan ] ; then
			stop
			start
		fi
	;;
  *)
	echo $"Usage: netplan {start|stop|status|restart|condrestart}"
	exit 1
esac

exit $RETVAL

