# $Id$
# Authority: shuff
# Upstream: Oleg G <oleg$cpan,org>

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name Net-HTTPS-NB

%define perl_prefix %{buildroot}%{_prefix}

Summary:  Non-blocking HTTPS client
Name: perl-Net-HTTPS-NB
Version:  0.13
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/Net-HTTPS-NB/

Source: http://search.cpan.org/CPAN/authors/id/O/OL/OLEG/Net-HTTPS-NB-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch

BuildRequires: perl
BuildRequires: perl(Exporter)
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(IO::Socket::SSL) >= 0.98
BuildRequires: perl(Net::HTTP) 
BuildRequires: perl(Net::HTTPS) 
BuildRequires: rpm-macros-rpmforge
Requires: perl
Requires: perl(Exporter)
Requires: perl(IO::Socket::SSL) >= 0.98
Requires: perl(Net::HTTP) 
Requires: perl(Net::HTTPS) 

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

# don't scan the examples for autoreq/prov
%filter_requires_in %{_docdir}
%filter_provides_in %{_docdir}

%description
Same interface as Net::HTTPS but it will never try multiple reads when the
read_response_headers() or read_entity_body() methods are invoked. In addition
allows non-blocking connect.

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{perl_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc Changes META.json README
%doc %{_mandir}/man?/*
%{perl_vendorlib}/Net/HTTPS/NB.pm
#%{perl_vendorlib}/Net/HTTPS/NB/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/*/*/.packlist

%changelog
* Thu Jan 30 2014 Steve Huff <shuff@vecna.org> - 0.13-1
- Initial package.
