# $Id$
# Authority: dag
# Upstream: Chris Elsworth <chris$shagged,org>

Summary: Top-like display of Apache logs
Name: apachetop
Version: 0.12
Release: 1
License: BSD
Group: Applications/Internet
URL: http://clueful.shagged.org/apachetop/

Source: http://clueful.shagged.org/apachetop/files/apachetop-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

BuildRequires: ncurses-devel, m4, readline-devel
Requires: httpd

%description
ApacheTop watches a logfile generated by Apache (in standard common or
combined logformat, although it doesn't (yet) make use of any of the extra
fields in combined) and generates human-parsable output in realtime.

%prep
%setup

%build
%configure \
	--with-logfile="%{_localstatedir}/log/httpd/access_log"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%makeinstall

%clean
%{__rm} -rf %{buildroot}

%files 
%defattr(-, root, root, 0755)
%doc AUTHORS ChangeLog LICENSE NEWS README TODO
%doc %{_mandir}/man1/apachetop.1*
%{_sbindir}/apachetop

%changelog
* Thu Aug 05 2004 Dag Wieers <dag@wieers.com> - 0.12-1
- Initial package. (using DAR)
