# $Id$
# Authority: shuff
# Upstream: David Precious <davidp$preshweb,co,uk>

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name Dancer-Plugin-Database

%define perl_prefix %{buildroot}%{_prefix}

Summary: Easy database connections for Dancer applications
Name: perl-Dancer-Plugin-Database
Version: 2.09
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/Dancer-Plugin-Database/

Source: http://search.cpan.org/CPAN/authors/id/B/BI/BIGPRESH/Dancer-Plugin-Database-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch

BuildRequires: perl
BuildRequires: perl(Dancer) >= 1.3099
BuildRequires: perl(Dancer::Plugin::Database::Core) >= 0.04
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: rpm-macros-rpmforge
Requires: perl
Requires: perl(Dancer) >= 1.3099
Requires: perl(Dancer::Plugin::Database::Core) >= 0.04

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

# don't scan the examples for autoreq/prov
%filter_requires_in %{_docdir}
%filter_provides_in %{_docdir}

%description
Provides an easy way to obtain a connected DBI database handle by simply
calling the database keyword within your Dancer application.

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{perl_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc Changes META.json README
%doc %{_mandir}/man?/*
%{perl_vendorlib}/Dancer/Plugin/Database.pm
#%{perl_vendorlib}/Dancer/Plugin/Database/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/*/*/.packlist

%changelog
* Fri Jan 31 2014 Steve Huff <shuff@vecna.org> - 2.09-1
- Initial package.
